{% set name = "nifty-tools" %}
{% set version = "0.3.3" %}
#{% set sha256 = "b2ada6f86faf5c9032e8b1a7b8cc0dff68a229e90ad80b366f5564fec03caa17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../
  #fn: nifty_tools-{{ version }}.tar.gz
  #url: https://github.com/DerThorsten/nifty_tools/archive/{{ version }}.tar.gz
  #sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - toolchain
    - cmake
    - nifty-meta


test:
  commands:
    - test -d ${PREFIX}/include/nifty/          # [unix]
    - test -d ${PREFIX}/include/nifty/tools  # [unix]
    - test -f ${PREFIX}/include/nifty/tools/tools.hpp  # [unix]
    - if exist %LIBRARY_PREFIX%\include\nifty\tools\tools.hpp (exit 0) else (exit 1)  # [win]


about:
  home: https://github.com/DerThorsten/nifty_tools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'nifty-tools'
  description: 'nifty-tools'
  documentation_url:  https://github.com/DerThorsten/nifty_tools
  dev_url: https://github.com/DerThorsten/nifty_tools

extra:
  recipe-maintainers:
    - DerThorsten
